name: Deploy

on: [push]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Running npm install
        run: npm install

      - name: Build site
        env:
          VITE_MONGODB_URL: ${{ secrets.VITE_MONGODB_URL }}
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_KEY: ${{ secrets.VITE_SUPABASE_KEY }}
        run: npm run build

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: 'minibase'
          entrypoint: './server.js' # same as `out` option in config
          root: 'build'
